apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-inbound-agent
  namespace: argocd-apps
  annotations:
    argocd.argoproj.io/ignore-resource-health: |
      networking.k8s.io/Ingress
spec:
  project: default
  sources:
    - repoURL: https://khangtictoc.github.io/jenkins-inbound-agent-helm-chart
      chart: jenkins-inbound-agent
      targetRevision: 0.7.0
      helm:
        valueFiles:
          - $values/argocd_values/jenkins-inbound-agent/values.yaml
    - repoURL: "https://github.com/khangtictoc/ArgoCD-Apps.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-inbound-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
