## Reference: https://artifacthub.io/packages/helm/bitnami/postgresql/18.0.17

## Including keys for:
# - adminPasswordKey: Admin password for user 'postgres'
# - userPasswordKey: User password for customed user defined at 'auth.user'
# - replicationPasswordKey: Replication password for replication user
auth:
  existingSecret: "postgresql" # Managed by "Vault Secret Operator"

## Secret Key mapping (DEFAULT)
# secretKeys:
#     adminPasswordKey: postgres-password
#     userPasswordKey: password
#     replicationPasswordKey: replication-password

replication:

primary:
  configuration: ""

readReplicas:
  replicaCount: 1
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "gp2" # For 'AWS' only

metrics:
  enabled: true
