# Reference: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
# Version: 11.1.1

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero-backup-eks
      config:
        region: us-east-1
      # credential:
      #   name: test
      #   key: test
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: us-east-1
      # credential:
      #   name: test
      #   key: test

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.1

metrics:
  enabled: true
  scrapeInterval: 30s
  scrapeTimeout: 10s
