# Reference: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
# Version: 11.1.1

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero-backup-kubernetes-aws
      config:
        region: us-east-1
      # credential:
      #   name: test
      #   key: test
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: us-east-1
      # credential:
      #   name: test
      #   key: test

# AWS Authentication via Pod Identity
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.1
    volumeMounts:
      - mountPath: /target
        name: plugins

serviceAccount:
  server:
    create: true
    name: velero-pod-identity

# Monitoring
metrics:
  enabled: true
  scrapeInterval: 30s
  scrapeTimeout: 10s
