# Reference: https://docs.nginx.com/nginx-ingress-controller/installation/installing-nic/installation-with-helm/#helm-chart-parameters
controller:
  kind: deployment
  logLevel: info
  ingressClass:
    name: nginx
  service:
    type: NodePort
    httpPort:
      nodePort: 30005
    httpsPort:
      nodePort: 30006
  reportIngressStatus:
    enableLeaderElection: true
  replicaCount: 1
  prometheus:
    create: true
    service:
      create: true
defaultVaultConnection:
  address: https://vault-testproject-dev-public-vault-5bc0f684.5869f18a.z1.hashicorp.cloud:8200
