# Reference: https://github.com/khangtictoc/jenkins-inbound-agent-helm-chart

agent:
  name: "Test1"
  workDir: "/home/jenkins/agent"
  jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
  jenkinsSecretName: "my-jenkins-secret"
