# Reference: https://github.com/khangtictoc/jenkins-inbound-agent-helm-chart

image:
  repository: "darkhero101/jenkins-inbound-agent-common"
  tag: "0.5.0"

agent:
  name: "General"
  workDir: "/home/jenkins/agent-general"
  jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
  jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
  jenkinsSecretName: "jenkins-inbound-agent-connectors"
  jenkinsSecretKey: JENKINS_AGENT_SECRET_GENERAL

livenessProbe: {}
readinessProbe: {}
