# Reference: https://artifacthub.io/packages/helm/hashicorp/vault-secrets-operator
defaultVaultConnection:
  enabled: true
  address: "https://vault-testproject-dev-public-vault-3187803a.46c4027f.z1.hashicorp.cloud:8200"
  skipTLSVerify: false
controller:
  manager:
    clientCache:
      persistenceModel: direct-encrypted
      storageEncryption:
        enabled: true
        mount: auth-mount
        keyName: vso-client-cache
        transitMount: transit-mount
        kubernetes:
          role: auth-role-operator
          serviceAccount: vault-secrets-operator-controller-manager
          tokenAudiences: ["vault"]
